# Generated by Django 3.0.4 on 2020-03-27 23:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('home_score', models.FloatField(default=0)),
                ('away_score', models.FloatField(default=0)),
                ('runner_log', models.TextField(blank=True, null=True)),
                ('_scheduled_task_id', models.CharField(max_length=36, null=True, verbose_name='scheduled task id')),
                ('away_robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='robots.Robot')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.Game')),
                ('home_robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='robots.Robot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
