- name: Install dependency packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add "{{ ansible_user }}" to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes
