# Generated by Django 3.0.3 on 2020-02-23 21:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nabard.storages
import robots.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(error_messages={'unique': 'A robot with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w\\.\\-]+$')], verbose_name='name')),
                ('code', models.FileField(blank=True, storage=nabard.storages.CodeStorage(), upload_to=robots.models.Robot.robot_code_path, validators=[django.core.validators.FileExtensionValidator(['py'])], verbose_name='code')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='games.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
