- name: Copy nginx configuration
  template:
    src: nginx.conf
    dest: "{{ deployment_path }}/nginx/nginx.conf"

- import_tasks: dns.yaml

- name: Setup Nginx
  become: yes
  docker_container:
    name: nabard-nginx
    image: nginx:{{ nginx_version }}
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "{{ deployment_path }}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
