- name: Ensure nginx configuration directory exists
  become: yes
  file:
    path: "{{ deployment_path }}/nginx"
    state: directory

- name: Copy nginx configuration
  become: yes
  template:
    src: nginx.conf.j2
    dest: "{{ deployment_path }}/nginx/nginx.conf"

- import_tasks: dns.yaml

- name: Setup Nginx
  become: yes
  docker_container:
    name: nginx-nabard
    image: nginx:{{ nginx_version }}
    restart_policy: always
    ports:
      - "80:80"
    links:
      - nabard-django:nabard-django
      - minio-nabard:s3
    volumes:
      - "{{ deployment_path }}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
