# Generated by Django 3.0.3 on 2020-02-21 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import games.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(error_messages={'unique': 'A game with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('instruction', models.TextField()),
                ('code', models.FileField(storage='nabard.storages.CodeStorage', upload_to=games.models.Game.game_code_path, validators=[django.core.validators.FileExtensionValidator(['py'])], verbose_name='code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
