name: Continuous Integration

on: [push, pull_request]

jobs:
  lint:
    name: Lint Checking
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Ansible lint
        run: pipenv run ansible-lint deploy/*.yaml

      - name: Python lint
        run: pipenv run pylama

  test:
    name: Test Execution
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: nabard_test
          POSTGRES_USER: nabard
          POSTGRES_PASSWORD: test_pass
        # Health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: nabardio/minio
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: NABARDACCESSKEY
          MINIO_SECRET_KEY: NabardSecretAcessKey
          MINIO_BUCKETS: codes

      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    env:
      APP_DB_HOST: localhost
      APP_DB_USER: nabard
      APP_DB_PASS: test_pass
      APP_DB_NAME: nabard_test
      APP_S3_ENDPOINT: http://localhost:9000
      APP_S3_ACCESS_KEY: NABARDACCESSKEY
      APP_S3_SECRET_KEY: NabardSecretAcessKey
      APP_CELERY_BROKER_URL: amqp://localhost

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Setup the database
        run: pipenv run ./manage.py migrate --noinput

      - name: Run tests
        run: pipenv run pytest
