name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  build:
    name: Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: nabardio/nabard-server
          tag_with_ref: true
          tags: latest

  deploy:
    needs: [build]
    name: Ansible Deployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Create ansible vault password file
        run: echo ${{ secrets.ANSIBLE_VAULT_PASS }} > vault-pass.txt
        working-directory: deploy

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Extract version
        run: echo ::set-env name=VERSION::$(git describe --tags)

      - name: Run ansible deploy.yaml playbook
        run: >-
          pipenv run
          ansible-playbook
          --vault-password-file vault-pass.txt
          --extra-vars nabard_version=$VERSION
          -i inventory.yaml
          deploy.yaml
        working-directory: deploy
